export const data = [
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Generic Soft Chips",
    price: "928.00",
    count: "8",
    id: "1",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Frozen Shoes",
    price: "897.00",
    count: "5",
    id: "2",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Rubber Keyboard",
    price: "222.00",
    count: "1",
    id: "3",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Awesome Fresh Tuna",
    price: "784.00",
    count: "1",
    id: "4",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Cotton Cheese",
    price: "972.00",
    count: "7",
    id: "5",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Rubber Shirt",
    price: "960.00",
    count: "8",
    id: "6",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Rustic Steel Shirt",
    price: "409.00",
    count: "3",
    id: "7",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Soft Keyboard",
    price: "783.00",
    count: "2",
    id: "8",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Unbranded Granite Towels",
    price: "134.00",
    count: "8",
    id: "9",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Small Plastic Pizza",
    price: "141.00",
    count: "6",
    id: "10",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Wooden Hat",
    price: "997.00",
    count: "9",
    id: "11",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Modern Soft Soap",
    price: "504.00",
    count: "6",
    id: "12",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Fantastic Steel Cheese",
    price: "190.00",
    count: "5",
    id: "13",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Small Granite Bike",
    price: "259.00",
    count: "2",
    id: "14",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Steel Towels",
    price: "220.00",
    count: "1",
    id: "15",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Practical Fresh Pants",
    price: "375.00",
    count: "6",
    id: "16",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Sleek Metal Computer",
    price: "971.00",
    count: "8",
    id: "17",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Steel Bacon",
    price: "85.00",
    count: "3",
    id: "18",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Practical Wooden Gloves",
    price: "564.00",
    count: "8",
    id: "19",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Intelligent Granite Chair",
    price: "456.00",
    count: "6",
    id: "20",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Licensed Plastic Keyboard",
    price: "731.00",
    count: "1",
    id: "21",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Frozen Bike",
    price: "172.00",
    count: "3",
    id: "22",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Unbranded Wooden Shoes",
    price: "170.00",
    count: "9",
    id: "23",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Bespoke Granite Shoes",
    price: "909.00",
    count: "7",
    id: "24",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Oriental Granite Soap",
    price: "442.00",
    count: "4",
    id: "25",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Tasty Fresh Hat",
    price: "704.00",
    count: "5",
    id: "26",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Recycled Bronze Towels",
    price: "580.00",
    count: "6",
    id: "27",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Ergonomic Concrete Shoes",
    price: "747.00",
    count: "8",
    id: "28",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Refined Frozen Hat",
    price: "290.00",
    count: "5",
    id: "29",
  },
  {
    image: "https://loremflickr.com/640/480/food",
    name: "Electronic Steel Keyboard",
    price: "616.00",
    count: "7",
    id: "30",
  },
];
